ros__parameters:
  preprocessing:
    data_structuring:
      enabled: true
      methods:
        GridMap:
          enabled: true
          parameters:
            gridmap_resolution: 0.1
        "3DGridMap":
          enabled: false
          parameters:
            voxel_size: 0.1
        Octree:
          enabled: false
          parameters:
            max_depth: 10
        KDTree:
          enabled: false
          parameters:
            K: 0.1
        Octomap:
          enabled: false
          parameters:
            octomap_resolution: 0.05
            octomap_filename: "/home/airsim_user/Landing-Assist-Module-LAM/lib/preprocessing/pointcloud.bt"

  hazard_metrices:
    PCA:
      enabled: true
      method: "PCA"
      parameters:
        voxel_size: 0.35
        slope_threshold: 5.0
        k: 10
    RANSAC_Open3D:
      enabled: true
      method: "RANSAC_Open3D"
      parameters:
        voxel_size: 0.1
        distance_threshold: 1.9
        ransac_n: 3
        num_iterations: 1000
    RANSAC_PCL:
      enabled: true
      method: "RANSAC_PCL"
      parameters:
        voxelSize: 0.15
        distanceThreshold: 1.9
        maxIterations: 1000
    PROSAC:
      enabled: true
      method: "PROSAC"
      parameters:
        voxel_size: 0.15
        distanceThreshold: 1.9
        maxIterations: 200
    LeastSquares_Open3D:
      enabled: true
      method: "LeastSquares_Open3D"
      parameters:
        voxel_size: 0.15
        distance_threshold: 1.85
    LMEDS:
      enabled: true
      method: "LMEDS"
      parameters:
        voxelSize: 0.15
        distanceThreshold: 1.9
        maxIterations: 100
    Average3DGradient:
      enabled: true
      method: "Average3DGradient"
      parameters:
        voxelSize: 0.1
        neighborRadius: 0.5
        gradientThreshold: 0.15
        angleThreshold: 10.0
    RegionGrowing:
      enabled: true
      method: "RegionGrowing"
      parameters:
        voxel_size: 0.45
    CalculateRoughness_PCL:
      enabled: true
      method: "CalculateRoughness_PCL"
      parameters:
        voxel_size: 0.15
        distanceThreshold: 1.9
        maxIterations: 200
    CalculateRoughness_Open3D:
      enabled: true
      method: "CalculateRoughness_Open3D"
      parameters:
        voxel_size: 0.1
        distance_threshold: 1.9
        ransac_n: 3
        num_iterations: 1000
    CalculateRelief_PCL:
      enabled: true
      method: "CalculateRelief_PCL"
      parameters:
        voxel_size: 0.15
        distanceThreshold: 1.9
        maxIterations: 200
    CalculateRelief_Open3D:
      enabled: true
      method: "CalculateRelief_Open3D"
      parameters:
        voxel_size: 0.1
        distance_threshold: 1.9
        ransac_n: 3
        num_iterations: 1000
    CalculateDataConfidence_PCL:
      enabled: true
      method: "CalculateDataConfidence_PCL"
      parameters:
        voxel_size: 0.15
        distanceThreshold: 1.9
        maxIterations: 200
    CalculateDataConfidence_Open3D:
      enabled: true
      method: "CalculateDataConfidence_Open3D"
      parameters:
        voxel_size: 0.01
        distance_threshold: 1.9
        ransac_n: 3
        num_iterations: 1000

  processing_order:
    hazard:
      - "RANSAC_Open3D"
      - "PCA"
      - "RANSAC_PCL"
      - "PROSAC"
      - "LeastSquares_Open3D"
      - "LMEDS"
      - "Average3DGradient"
      - "RegionGrowing"
      - "CalculateRoughness_PCL"
      - "CalculateRoughness_Open3D"
      - "CalculateRelief_PCL"
      - "CalculateRelief_Open3D"
      - "CalculateDataConfidence_PCL"
      - "CalculateDataConfidence_Open3D"
