ros__parameters:
  # pcd_file_path: "/home/airsim_user/Landing-Assist-Module-LAM/test.pcd"
  pcd_file_path: "/home/airsim_user/Landing-Assist-Module-LAM/test.pcd"
  visualize: false #visualization for individual function
  final_visualize: true #visualizing final result
  final_result_visualization: "both" # can choose both ,inlier_cloud,outlier_cloud to visualize
  voxel_size: 0.45
  voxel_downsample_pointcloud: true


  # Define the pipeline of processing steps.
  pipeline:
    - step: "SOR"
      enabled: true
      parameters:
        nb_neighbors: 20
        std_ratio: 2.0
        visualization: "both"
    - step: "Radial"
      enabled: false
      parameters:
        voxel_size: 0.05
        radius_search: 0.9
        min_neighbors: 50
        visualization: "both"
    - step: "Bilateral"
      enabled: false
      parameters:
        voxel_size: 0.05
        sigma_s: 15
        sigma_r: 0.3
        visualization: "both"
    - step: "PROSAC"
      enabled: true
      parameters:
        voxel_size: 0.05
        distanceThreshold: 1.9
        maxIterations: 1000
        visualization: "both"
    - step: "LMEDS"
      enabled: false
      parameters:
        voxel_size: 0.05
        distanceThreshold: 1.9
        maxIterations: 1000
        visualization: "both"
    - step: "PCA"
      enabled: false
      parameters:
        voxelSize: 0.05
        angleThreshold: 10.0
        k: 10
        visualization: "both"
    - step: "CheckSLZ-r"
      enabled: false
      parameters:
        landingRadius: 0.015
        removalThreshold: 0.01
        clusterTolerance: 0.8 # in m
        visualization: "both"
 
